# Generated by Django 5.2.1 on 2025-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
                ('number_type', models.CharField(max_length=50)),
                ('agent_extension', models.CharField(max_length=10)),
                ('dial_result', models.CharField(max_length=50)),
                ('call_disposition', models.CharField(max_length=50)),
                ('callback', models.CharField(max_length=50)),
                ('ring_duration', models.IntegerField()),
                ('talk_duration', models.IntegerField()),
                ('call_duration', models.IntegerField()),
                ('uid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ring_duration', models.IntegerField()),
                ('talk_duration', models.IntegerField()),
                ('call_duration', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('outbound_caller_id', models.CharField(max_length=50)),
            ],
        ),
    ]
