# Generated by Django 5.2.1 on 2025-05-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialer_reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='campaignrecord',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dialer_reports.campaign'),
        ),
        migrations.AddField(
            model_name='campaignrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_cdrs', to='dialer_reports.campaign'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='campaign_record',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='dialer_reports.campaignrecord', to_field='uid'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
